### PR TITLE
Consolidate Jekyll setup instructions

### PR DESCRIPTION
**Pull request by pearswj**
I've been through the process on a fresh OS X Yosemite and Windows 8.1 (my new rMBP arrived this afternoon :smile:) and the following works™. If it reads well, pull it in. If not, well it was an interesting exercise for a Tuesday evening.

/cc @dbelcher @scotttd @acormier @sbaer (side note: should we be using GitHub orgs to make sure the right people are mentioned?)

### CODE REVIEW

**Comment by dbelcher** [comment]
Awesome, thanks for going through this on a "fresh" OS X machine and consolidating the instructions.

> the following works™

Ummm...I believe the proper "Mac" way of saying this is: "the following _just_ works™"

> (side note: should we be using GitHub orgs to make sure the right people are mentioned?)

Let's do it.  Wait...I dunno how.

**Comment by sbaer** [comment]
https://github.com/blog/1121-introducing-team-mentions

I think this is what Will is alluding to.

**Comment by sbaer** [comment]
why is it not wise to just use ruby and ruby gems pre-install on OS X?

**Comment by acormier** [comment]
That sounds really useful

**Comment by pearswj** [comment]
The built-in ruby won't let you install anything using ruby gems. The only option is to throw `sudo` at the problem but if you know what you're doing with `sudo` then you don't need the instructions!

```
MacBook-Pro:~ will$ /usr/bin/ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]          
MacBook-Pro:~ will$ /usr/bin/gem --version
2.0.14
MacBook-Pro:~ will$ /usr/local/bin/gem --version
2.4.5
MacBook-Pro:~ will$ /usr/bin/gem install pg
Fetching: pg-0.18.2.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
```

`/usr/local/bin/` is where Homebrew installs things (well, symlinks them to...).

**Comment by pearswj** [comment]
> Let's do it. Wait...I dunno how.
@dbelcher I'm forever torn between trying out new features and just keeping it simple. Can you give me the necessary permissions so we can look into it together?

**Comment by pearswj** [comment]
And [this](https://github.com/orgs/improved-permissions?utm_source=github_site&utm_medium=blog&utm_campaign=organization-permissions).

Anyway, I'm sure you've got plenty on and it's way past my bedtime!

**Comment by dbelcher** [comment]
Ok @mcneel/devdocs I think I have this team member mention thing working.  Lemme know if you get this mention.  

@pearswj you should have Admin permissions already in McNeel.

**Comment by pgolay** [comment]
I got it...

-Pascal

Pascal Golay
pascal@mcneel.com
www.rhino3d.com
206 545 9260

**Pull request merged**
