### PR TITLE
remove seemingly erroneous text from macrhi guide

### PR DESCRIPTION
**Pull request by pearswj**

### CODE REVIEW

**Comment by pearswj** [comment]
Perhaps the overview should also mention renaming the `*.dll` to `*.rhp`...

**Comment by pearswj** [comment]
Oh wait, _what?!_ You add the `*.rhp` extension to the _folder_?

**Comment by dbelcher** [comment]
Yes, you rename the folder.  I agree, this is a little counter-intuitive.  Knowing this, do you think the directions are still misleading?  Reading it again, I think the Step-by-Step instructions are correct...the overview might be made to be more clear.  I think your edit makes it less clear.

**Comment by dbelcher** [comment]
@pearswj On second thought, the Overview does seem misleading.  I made some changes.  Thanks for pointing these out.

**Comment by fraguada** [comment]
What is the advantage of renaming the folder?  I've always just renamed the dll and it works fine. Don't recall at the moment,  but does the mac plugin template automatically do this renaming in a post - build?

**Comment by dbelcher** [comment]
You can have multiple plugin dlls in a folder.  Also, when renamed, the
folder becomes what is called a "bundle" on OS X and is treated
appropriately.

The mac plugin template does not automatically do this renaming in a
post-build event.

**Comment by sbaer** [comment]
Both techniques will work, but renaming the folder has a couple advantages:
- On OSX, a folder that ends with .rhp is displayed as a plug-in bundle in finder. This is probably not that big of a deal since the plug-ins in general are in a relatively hidden location on the user's computer
- Keeping the DLL extension means that the debugging information file (mdb) is correctly named. If you choose to ship the mdb along with the dll, I can get better stack information out of your plug-in for crash/exception reports.

**Comment by fraguada** [comment]
@sbaer @dbelcher Thanks for the clarification.

**Pull request closed without merging**
