### PR TITLE
Fix version banner to top of page and remove "click here"

### PR DESCRIPTION
**Pull request by pearswj**
@dbelcher, @golsby: Please see http://developer.rhino3d.com/demo/

screen shot 2016-05-10 at 12 37 19

Code attached but I might do a _ninja_ merge into both `master` and `wip`...

### CODE REVIEW

**Comment by dbelcher** [comment]
Nice!  One small weird thing...when I'm at the top of the page, the bar and the background bar have different vertical sizes.  This is in Chrome:
screen shot 2016-05-10 at 3 26 03 pm

**Comment by dbelcher** [comment]
Ahh...I see what is happening.  It's still showing the little horizontal band of color that was always at the top of the page...just remove it.  I think @golsby hated that little band anyway.

**Comment by pearswj** [comment]
OK, will do!

**Comment by dbelcher** [comment]
Too slow!

**Comment by dbelcher** [comment]
Looks good to me.  What do you think @golsby ?

**Comment by golsby** [comment]
I like what's discussed... I presume I need to pull and run my own version of the site to see this? I don't see the change on the published version of the web site.

**Comment by pearswj** [comment]
@golsby: I manually pushed it to developer.rhino3d.com/demo

**Comment by pearswj** [comment]
Closed #72 via b081bd1 and d2bfab7.

**Pull request closed without merging**
